name: Teste Bot Threads

on:
  workflow_dispatch: # Libera o botão para testar manualmente

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o código do repositório
        uses: actions/checkout@v4

      - name: Instalando o Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Instalando as bibliotecas do bot
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executando o script do Threads
        env:
          THREADS_USER_ID: ${{ secrets.THREADS_USER_ID }}
          THREADS_TOKEN: ${{ secrets.THREADS_TOKEN }}
        run: python bluesky_bot.py  # Mantive o nome do seu arquivo antigo aqui!
