name: Teste Schedule

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Confirmando execução automática
        run: |
          echo "Rodou pelo GitHub Actions"
          date -u
